# Generated by Django 6.0.2 on 2026-02-23 16:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('national_id', models.CharField(help_text='Kenya National ID Number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'Enter a valid National ID (7-8 digits)')])),
                ('phone_number', models.CharField(help_text='Phone number in format: +254XXXXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')])),
                ('role', models.CharField(choices=[('INITIATOR', 'Initiator (Dr. Amani - Health Director)'), ('CHIEF_OFFICER', 'Chief Officer - Health (Madam Joy)'), ('COUNTY_SECRETARY', 'County Secretary (Mr. Kiplagat)'), ('CPSB_BOARD', 'CPSB Board Member'), ('CPSB_SECRETARIAT', 'CPSB Secretariat'), ('HR_SECRETARIAT', 'HR Secretariat'), ('HR_ADMIN', 'HR Administrator'), ('PANELIST', 'Interview Panelist'), ('PAYROLL_OFFICER', 'Payroll Officer')], default='INITIATOR', max_length=30)),
                ('department', models.CharField(blank=True, default='Health', max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='accounts.user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'permissions': [('can_approve_requisitions', 'Can approve requisitions'), ('can_endorse_requisitions', 'Can endorse requisitions'), ('can_board_approve', 'Can approve at board level'), ('can_shortlist', 'Can shortlist candidates'), ('can_interview', 'Can conduct interviews'), ('can_verify_documents', 'Can verify candidate documents'), ('can_generate_offers', 'Can generate appointment letters'), ('can_export_payroll', 'Can export payroll data')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.user')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
